# Generated by Django 6.0.3 on 2026-03-22 10:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_studysession_legacy_subject_assignment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['user', 'deadline'], name='student_ass_user_id_6ba99a_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['user', 'is_completed', 'deadline'], name='student_ass_user_id_4ff08e_idx'),
        ),
        migrations.AddIndex(
            model_name='studysession',
            index=models.Index(fields=['user', 'created_at'], name='student_stu_user_id_d0e76d_idx'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(condition=models.Q(('duration__gt', 0)), name='chk_studysession_duration_gt0'),
        ),
        migrations.AddConstraint(
            model_name='studysession',
            constraint=models.CheckConstraint(condition=models.Q(('focus_level__gte', 0), ('focus_level__lte', 100)), name='chk_focus_0_100'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_subject_user_name'),
        ),
    ]
